function G(a,d,e){function h(){0!=I&&(K=(new Date).getTime()-I)}function n(f){F=F|f;A.narme=F}function l(f){p.a("l2("+f+")");E=E|f;S()?(h(),I=0):0==I&&(I=(new Date).getTime());A.narm=E;p.a("l2e")}function r(f){L=L|f;A.naral=L}var p=new P,c=e&&e.dvObj||window.$dv,k=e&&e.impressionId||window.$uid,v=window.Of||d,q=Array(v.hb),g=v.Wa/v.Wb+1,b=null,u="",x={},f=0,t=Array(v.hb),m={ea:{I:null,J:null,D:null,C:null,Oe:!1},f:{v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,Oe:!1},va:{zb:null,yb:null},
Fb:0},w={},C={},B,y,z={},N={},J=null;this.Cb=function(f){if(null==J||1==J||8==J)J=f};for(d=0;d<v.hb;d++)t[d]="b"+d;var D={};e&&c&&c.CommonData&&(D.ctx=e.jb,D.cmp=e.ib,D.btreg=e.btreg,D.btadsrv=e.Ja,D.uid=e.ob,D.brid=c.CommonData.BrowserId,D.brver=c.CommonData.BrowserVersion,D.tstype=c.CommonData.Scenario);D.jsver=a?a:null;var A={},H={},I=0,K="",M="",L=0,E=0,F=0,O=0;this.Oc=function(){return I};this.rd=function(f){O=O|f;A.vct=O};this.qd=function(f){b=f;H.strp=b;this.qd=function(){}};this.$b=function(){return(new Date).getTime()};
var T=this.$b();this.Ee=function(){return T};this.pf=function(){E=E&-3;F=F&-2;F&=-3};this.Bb=function(){l(2)};this.Af=function(){n(8);this.pc()};this.pc=function(){l(4)};this.md=function(){r(8);this.Bb()};this.xd=function(f){r(16);A.dbg9=f};this.yd=function(){r(1)};this.yf=function(){this.Bb();n(1)};this.xf=function(){this.Bb();n(2)};this.Za=function(f,b){l(8);M=p.xe(f,b)};this.uf=function(){p.a("l1");E=E&-3;l(1);p.a("l1e")};this.pd=function(){l(16)};this.re=function(){return q};this.nd=function(b,
a){k=k||e&&e.impressionId||window.$uid;p.a("ie15");if(0<=b.m){var m=Math.floor(b.m/v.Wb);0<b.m%v.Wb?m++:0<b.m&&m++;isNaN(q[m])&&(q[m]=0);q[m]+=a;b.P&&m>=g||0==b.P&&6<=m?f+=a:(timeStampTotalBuckets=f=0,this.Cb(7))}p.a("ie15e")};this.wf=function(f){var b=f.Vc;null!=f.Vc&&(w.advisonl=b);null!=f.Uc&&(w.adabvvponl=f.Uc);A.dbg8="CSS1Compat"===document.compatMode?1:0;p.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(A.dbg10=document.documentMode);p.a("ff52e")};this.Ya=function(f){p.a("ie14");
null!=f&&(N.adbtftopg=f)};this.vf=function(f){null!=f&&(m=f)};this.od=function(f){p.a("ie19");this.vf(f.s);this.Cf();p.a("ie19e")};this.Bd=function(){null!=m.ea.I&&(z.vptoscrx=Math.round(m.ea.I));null!=m.ea.J&&(z.vptoscry=Math.round(m.ea.J));null!=m.ea.D&&(z.vpwdth=Math.round(m.ea.D));null!=m.ea.C&&(z.vphgt=Math.round(m.ea.C));null!=m.f.v&&(z.adtovpx=Math.round(m.f.v));null!=m.f.u&&(z.adtovpy=Math.round(m.f.u));null!=m.f.K&&(z.adtopgx=Math.round(m.f.K));null!=m.f.L&&(z.adtopgy=Math.round(m.f.L));
null!=m.f.G&&(z.adtoscrx=Math.round(m.f.G));null!=m.f.H&&(z.adtoscry=Math.round(m.f.H));null!=m.va.zb&&(z.scrwdth=Math.round(m.va.zb));null!=m.va.yb&&(z.scrhgt=Math.round(m.va.yb));z.almesind=m.Fb};this.Cd=function(){if(B&&y){var f=null!=m.f.o?m.f.o:null,b=null!=m.f.i?m.f.i:null;0>B*y&&(C.dvp_adwdth=B,C.dvp_adhgt=y,B=f,y=b)}else B=null!=m.f.o?m.f.o:null,y=null!=m.f.i?m.f.i:null;null!=B&&(C.adwdth=B);null!=y&&(C.adhgt=y)};this.Cf=function(){h();for(var f=0;f<q.length;f++)q[f]&&(x[t[f]]=q[f]);this.Bd();
this.Cd();p.F(z,w);p.F(z,C);p.F(z,N)};this.Mc=function(){if(1E3<=f)return!0;this.Cb(8);return!1};this.Be=function(f){var b={};k=k||e&&e.impressionId||window.$uid;var g=-1,a=p.ye();try{c&&c.tags[k]&&c.tags[k].getTimeDiff&&(g=c.tags[k].getTimeDiff())}catch(m){}var q=[];p.F(b,D);switch(f){case 1:u=g;p.F(b,H);p.F(b,A);b.napt=K;p.F(b,z);b.dvp_log=a;b.napr=M;b.ismms=u;b.isumms=g;break;case 2:p.F(b,H);p.F(b,A);b.napt=K;p.F(b,z);b.dvp_log=a;b.napr=M;b.isnmms=g;break;case 3:b.istoms=g,b.nvr=J;case 4:case 8:p.F(b,
H);p.F(b,N);p.F(b,C);b.isbxdms=g;p.F(b,x);b.nvr=J;break;case 5:p.F(b,H);p.F(b,N);p.F(b,C);p.F(b,w);b.ismms=u||g;b.isiabvms=g;b.isuiabvms=g;break;case 16:p.F(b,H);p.F(b,A);b.napt=K;b.dvp_log=a;b.napr=M;b.ishems=g;break;case 7:return q.join("");default:p.F(b,H),p.F(b,x),p.F(b,A),p.F(b,w),b.napt=K,b.dvp_log=a,b.napr=M}b.evid=f;b.ctime=this.$b();return b};this.qe=function(){p.a("ie17");for(var f=[],b=0;b<v.hb;b++)f[b]=q[b]?q[b]:0;return f};var S=this.Gc=function(){return 2==(E&2)&&8!=(L&8)||4==(E&4)||
8==(F&8)&&8==(L&8)?!1:!0};this.gf=function(f){p.a("l3");f=p.aa(f);p.a("cm3e");f&&(A.dbg5=f.w,A.dbg6=f.h);p.a("l3e")};return this}function Q(a,d){var e=new P,h=a&&a.impressionId||window.$uid;this.da=function(a,l){if(d){var r=d.Be(a);l&&e.F(r,l);var p=!1;if(4==a||8==a)p=!0;this.ld(h,r,p)}};this.ld=function(a,d,e){$dv&&$dv.registerEventCall&&a&&$dv.registerEventCall(a,d,null,null,e)}}function R(){this.da=function(){};this.ld=function(){}}
function U(a,d,e,h){function n(){if(1==m){try{for(var b in f)t.removeChild(f[b]);u.document.body.removeChild(t)}catch(g){}m=!1}}function l(f){f=f||0;var b=c(0);b.Yc()?7<b.nb()?(n(),C=w=m=!1):(m=!0,w=!1):20>f?(f++,setTimeout(l,50,f)):(m=w=C=!1,n())}function r(f){$dv&&$dv.tags&&$dv.tags[h]&&$dv.tags[h].getTimeDiff&&$dv.tags[h].getTimeDiff();if(null!==f.eb)for(var b=0;b<f.eb.length;b++){var g=c(b).nb();0==b?g>B&&(B=g):g>y&&(y=g)}}function p(f){for(var b=!0,g=0;13>=g;g++)var k=c(g),b=b&(null!==k&&k.Yc());
if(!b)return null;f.Dc=0;f.nc=0;f.mc=0;f.gc=0;f.Ca=0;f.eb=Array(13);b=c(0).nb();for(g=1;13>=g;g++)if(k=5<Math.abs(c(g).nb()-b),f.eb[g]=k)switch(f.Dc++,g){case 2:case 3:case 4:case 5:f.nc++;break;case 6:case 7:case 8:case 9:f.mc++;break;case 10:case 11:case 12:case 13:f.gc++}if(13===f.Dc)return f.Ca=100,r(f),!0;b=f.eb;if(!1===b[1]){if(3<=f.gc||3<=f.mc||3<=f.nc)return r(f),null;f.Ca=0;r(f);return!1}if(!0===b[1]&&(!0===b[2]&&!0===b[3]||!0===b[2]&&!0===b[4]||!0===b[3]&&!0===b[5]||!0===b[4]&&!0===b[5])||
!0===b[1]&&4==f.mc||!0===b[1]&&4==f.gc&&1<=f.nc)return f.Ca=50,r(f),!0;if(b[2]&&b[5]&&!(b[6]&&b[10]&&b[1]&&b[13]&&b[9])||b[4]&&b[3]&&!(b[8]&&b[12]&&b[1]&&b[11]&&b[7]))return r(f),null;f.Ca=0;r(f);return!1}function c(b){b=f[b];var g=null;b&&(g=b.contentWindow);return g}function k(){for(var b=x.getBoundingClientRect(),k=b.width,a=b.height,m=k/(1+q),c=a/(1+q),t=k/q,v=a/q,u=0;13>=u;u++){var d=b.left,e=b.top;switch(u){case 0:e=d=-1E5;break;case 1:d+=(k-g)/2;e+=(a-g)/2;break;case 3:d+=k-g;break;case 4:e+=
a-g;break;case 5:d+=k-g;e+=a-g;break;case 6:d+=(k-t)/2;e+=(a-v)/2;break;case 7:d+=(k-t)/2+t;e+=(a-v)/2;break;case 8:d+=(k-t)/2;e+=(a-v)/2+v;break;case 9:d+=(k-t)/2+t;e+=(a-v)/2+v;break;case 10:d+=(k-m)/2;e+=(a-c)/2;break;case 11:d+=(k-m)/2+m;e+=(a-c)/2;break;case 12:d+=(k-m)/2;e+=(a-c)/2+c;break;case 13:d+=(k-m)/2+m,e+=(a-c)/2+c}6<=u&&(d-=g/2,e-=g/2);var w=f[u];w.style.left=d+"px";w.style.top=e+"px"}}function v(){if(null!=x&&null!=x.parentNode){w=!0;t=u.document.createElement("div");u.document.body.appendChild(t);
for(var b=0;13>=b;b++){var a=u.document.createElement("iframe");a.width=g;a.height=g;a.style.position="absolute";a.frameBorder="0";a.style.visibility="hidden";a.style.zIndex=-9999999;a.style.display="block";a.src="javascript:no=false;yes=true;("+function(){window.$e={Zd:100};window.Kc=no;window.bb=0;window.Tc=0;window.bd=0;window.Rf=no;window.nb=function(){return window.bd};window.Yc=function(){return window.Kc};window.Ue=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Rb=function(){window.bb++;window.Ue(window.Rb,document)};window.Rb();setInterval(function(){10>window.bb&&window.Rb();window.bd=window.bb-window.Tc;window.Tc=window.bb},window.$e.Zd);window.setTimeout(function(){window.Kc=yes},250)}.toString()+")();";t.appendChild(a);f.push(a)}k()}}var q=Math.sqrt(2),g=1,b=new P,u=null,x=null,f=[],t,m=!1,w=!1,C=b.ub(a,d,e);0==b.Ua()&&(g=8);var B=0,y=0;this.Ke=function(){0==w&&(0==(this.Va()&&(null!=x&&b.Xc(x,u)?!0:!1))?m=!1:(v(),
l()))};this.Va=function(){return C};this.Re=function(){return m};this.sd=function(f,b){u=f;x=b;this.Ke()};this.He=function(){if(0==m)return null;var f={};return null==p(f)?null:f.Ca}}
function V(a,d,e,h,n,l,r,p){this.b=new P;this.window=a;this.c=d;this.R=e;this.M=h;this.Z=r&&r.Enums.BrowserId||window.$dv.Enums.BrowserId;this.W=r&&r.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.N=n;this.ec=l;this.ga=null;this.Sc=this.window?this.b.vb(this.window.top):this.b.vb(window.top);this.Ne=this.R!=this.W.CrossDomain&&this.b.lb("ofs")&&this.Sc;this.ga=new U(this.R,this.M,r,p);null!=this.ga&&this.ga.Va()&&this.ga.sd(this.window,this.c);this.qb=this.wb=this.pa=null;this.rb=!1;
var c=0;this.ia={Nd:1,Od:2,Id:4,Kb:8,Hd:16,Lb:32,Md:64};this.oc=function(k,a,c,g){if(g&&g.insertBefore&&g.firstChild&&(k=this.window.document.createElement(k))){for(var b in a)k[b]=a[b];for(b in c)k.style[b]=c[b];g.insertBefore(k,g.firstChild);return k}return null};this.oe=function(a,c,q){var g=this.window.top,b=a.width,u=a.height;0>q.left?(b=a.width-Math.abs(q.left),0>c.Aa&&(b-=Math.abs(c.Aa))):0>c.Aa&&(b=a.width-Math.abs(c.Aa)+q.left,b=b>a.width?a.width:b);var d=a.width,f=Math.min(this.b.ya(g.window).clientWidth,
g.innerWidth),t=screen.availWidth-f-c.Aa,m=0;b<d?(d=b,m=f-b,0>c.Aa&&(m-=Math.abs(c.Aa))):m=f-d-q.left;0>m?(b=d-Math.abs(m),0>t&&(b-=Math.abs(t))):0>t&&(b=d-Math.abs(t)+m,b=b>d?d:b);c=screen.availHeight-c.qf-g.outerHeight;g=Math.min(this.b.ya(g.window).clientHeight,g.innerHeight)-a.height-q.top;0>g?(u=a.height-Math.abs(g),0>c&&(u-=Math.abs(c))):0>c&&(u=a.height-Math.abs(c)+g,u=u>a.height?a.height:u);0>q.top&&(u-=Math.abs(q.top));return{Ff:b,Gf:u}};this.Zb=function(a,c,q,g){var b=q.D,u=q.C,d=0;q=0;
var f={width:c.right-c.left,height:c.bottom-c.top};if(0>c.bottom||0>c.right||c.top>u||c.left>b||0>=f.width||0>=f.height)return 0;0>c.top?Math.abs(c.top)>=f.height?d=f.height:(d=f.height+c.top,d>u&&(d=u)):d=c.top+f.height>u?u-c.top:f.height;0>c.left?Math.abs(c.left)>=f.width?q=f.width:(q=f.width+c.left,q>b&&(q=b)):q=c.left+f.width>b?b-c.left:f.width;this.Ne&&(a=this.oe(f,a,c),q=a.Ff,d=a.Gf);return 0>=q||0>=d?0:Math.round(q*d/(f.width*f.height)*(g?f.width*f.height/((g.right-g.left)*(g.bottom-g.top)):
1)*100)};this.Yb=function(a,c){try{var q={x:a.offsetLeft,y:a.offsetTop},g;a.offsetParent?(g=this.Yb(a.offsetParent,c),q.x+=g.x,q.y+=g.y):c!=c.parent&&this.b.Mb(c,c.parent)&&(g=this.Yb(c.frameElement,c.parent),q.x+=g.x,q.y+=g.y);return q}catch(b){return{x:null,y:null}}};this.na=function(a){if(this.R==this.W.CrossDomain)if(this.b.ua(this.window)&&this.window.$sf.ext.geom)this.na=function(){var f=this.b.La(this.window),b=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-
parseInt(f.win.h):this.N.Explorer.X,g={D:null,C:null,I:null,J:null,j:!1};g.D=parseInt(f.win.w);g.C=parseInt(f.win.h);g.I=parseInt(f.win.l);g.J=parseInt(f.win.t)+b;g.j=!0;return g};else if(this.M.Y==this.Z.Firefox)this.na=function(){var f=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,b=f?0:this.window.screenX-screen.left,f=f?0:this.window.screenY-screen.top,g={D:null,C:null,I:null,J:null,j:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-this.N.Firefox.X;g.I=b;g.J=
f+this.N.Firefox.X;g.j=!0;return g};else if(this.b.jc(this.window)){var c=this;this.window.context.observeIntersection(function(f){f.forEach(function(f){c.pa=f})});this.na=function(){var f={D:null,C:null,j:!1,I:null,J:null};null!=this.pa?(f.D=this.pa.rootBounds.width,f.C=this.pa.rootBounds.height):(f.D=0,f.C=0);f.j=!0;return f}}else if(this.M.Y==this.Z.IE&&/^[11|12]/.test(this.M.ta))this.na=function(){var f=-8==this.window.screenY&&-8==this.window.screenX,b=f?0:this.window.screenX,f=f?0:this.window.screenY,
g={D:null,C:null,I:null,J:null,j:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-this.N.Explorer.X;g.I=b;g.J=f+this.N.Explorer.X;g.j=!0;return g};else if(this.M.Y==this.Z.IE&&/[6-9]|[10]/.test(this.M.ta)){var q=this.oc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,je:0,Ve:"0",We:"0"},{display:"inline",position:"absolute",top:0,left:0,Ef:"none",zIndex:0,border:0},this.window.document.body),g=this.oc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,je:0,Ve:"0",We:"0"},{display:"inline",
position:"absolute",top:0,left:0,Ef:"none",zIndex:0,border:0},this.window.document.body),b=g.contentWindow||g.window||g.contentDocument.window||g.contentWindow.window||this.window.Jf,d=q.contentDocument||q.contentWindow.document,q=g.contentDocument||g.contentWindow.document,e="<html><head><script >window.onload = "+function(f){f&&(window.event=f);isFinite(String(window.event.clientY))&&(parent.Ra={Pb:window.event.clientY,Ob:window.event.clientX,Ad:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",g='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(f){f&&(window.event=f);isFinite(String(window.event.clientY))&&(parent.qa={Pb:window.event.clientY,Ob:window.event.clientX,Ga:window.event.screenY-window.event.y,Fa:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";q.open("text/html","replace");q.write(g);q.close();
d.open("text/html","replace");d.write(e);d.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.na=function(){b.runMoM();d.open("text/html","replace");d.write(e);d.close();var f=this.window.qa,g=this.window.Ra,a=screen.availWidth,c=screen.availHeight,g=g?g.Ad:this.N.Explorer.X;if(f){var k=f.Fa,q=f.Ga;f.Fa>=a&&(f.Fa-=a);f.Ga>=c&&(f.Ga-=c);var v={D:null,C:null,I:null,J:null,j:!1};v.D=this.window.outerWidth?this.window.outerWidth-
20:a-f.Fa-20;v.C=this.window.outerHeight?this.window.outerHeight-g-10:c-f.Ga-10;v.I=k;v.J=q;v.j=!0}else v={D:null,C:null,I:null,J:null,j:!1},v.D=this.window.outerWidth?this.window.outerWidth-20:a-20,v.C=this.window.outerHeight?this.window.outerHeight-g-10:c-10,v.I=null,v.J=null,v.j=!1;return v}}else this.b.tb()?(this.hd(),this.na=function(){this.rb||this.hd();var f={D:null,C:null,I:null,J:null,j:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Chrome.X;f.j=!1;return f}):this.na=this.M.Y==
this.Z.Chrome?function(){var f={D:null,C:null,I:null,J:null,j:!1},b=!1;try{f.D=this.window.frameElement.offsetParent.parentNode.clientWidth,f.C=this.window.frameElement.offsetParent.parentNode.clientHeight,b=!0}catch(g){}f.I=this.window.screenX;f.J=this.window.screenY;f.j=b;return f}:null!=this.ga&&this.ga.Va()?function(){var f={D:null,C:null,I:null,J:null,j:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Safari.X;f.j=!1;return f}:function(){return{D:null,C:null,I:null,J:null,j:!1}};
else this.na=function(){var f,b,g=this.window.top;void 0!=g.mozInnerScreenX&&null!=g.mozInnerScreenX?(f=g.mozInnerScreenX,b=g.mozInnerScreenY):void 0!=g.screenX&&null!=g.screenX?0!=g.screenLeft+8&&g.screenLeft+8!=screen.width||0!=g.screenTop+8&&g.screenTop+8!=screen.height?(f=g.screenLeft,b=g.screenTop+(g.outerHeight-g.innerHeight)):(f=g.screenLeft+8,b=g.screenTop+(g.outerHeight-g.innerHeight)+8):(f=g.screenLeft,b=g.screenTop);var a={D:null,C:null,I:null,J:null,j:!1},c=this.b.ya(g);a.D=g.innerWidth||
c.clientWidth;a.C=g.innerHeight||c.clientHeight;a.I=f;a.J=b;a.j=!0;return a};return this.na(a)};this.ma=function(a,d){c=1;this.R==this.W.CrossDomain?this.b.ua(this.window)&&this.window.$sf.ext.geom&&this.b.La(this.window).par?(c=8,this.ma=function(){var a=this.b.La(this.window),g=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(a.win.h):this.N.Explorer.X,b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null};
b.v=parseInt(a.self.l)-parseInt(a.par.l);b.u=parseInt(a.self.t)-parseInt(a.par.t);b.K=parseInt(a.self.l);b.L=parseInt(a.self.t);b.G=parseInt(a.win.l)+b.v;b.H=parseInt(a.win.t)+b.u+g;b.o=parseInt(a.self.w);b.i=parseInt(a.self.h);b.j=!0;b.rect={top:b.u,bottom:b.u+b.i,left:b.v,right:b.v+b.o};return b}):this.M.Y==this.Z.Firefox?this.ma=function(){var a=1;window.devicePixelRatio&&(a=window.devicePixelRatio);var g=this.window.screenX,b=this.window.screenY,c=this.window.mozInnerScreenX/a-g,a=this.window.mozInnerScreenY/
a-b-this.N.Firefox.X,c={left:c,top:a,right:c+this.window.innerWidth,bottom:a+this.window.innerHeight},a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null};a.v=c.left;a.u=c.top;a.K=null;a.L=null;a.G=g+c.left;a.H=b+c.top;a.o=this.window.innerWidth;a.i=this.window.innerHeight;a.j=!0;a.rect=c;this.b.Eb()&&(a=this.kb(a));return a}:this.b.jc(this.window)?(c=32,this.ma=function(){var a={v:null,u:null,o:null,i:null,j:!1,rect:null,O:null,oa:null,K:null,L:null,G:null,H:null};
null!=this.pa?(a.v=this.pa.boundingClientRect.left,a.u=this.pa.boundingClientRect.top,a.o=this.pa.boundingClientRect.width,a.i=this.pa.boundingClientRect.height):(a.v=0,a.u=0,a.o=0,a.i=0);a.j=!0;a.rect={top:a.u,bottom:a.u+a.i,left:a.v,right:a.v+a.o};return a}):this.M.Y==this.Z.IE&&/^[11|12]/.test(this.M.ta)?this.ma=function(a){var g=this.window.screenLeft-window.screenX,b=this.window.screenTop-window.screenY-this.N.Explorer.X,g={left:g,top:b,right:g+this.window.innerWidth,bottom:b+this.window.innerHeight},
b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null};b.v=g.left;b.u=g.top;b.K=null;b.L=null;b.G=a.I+g.left;b.H=a.J+g.top;b.o=this.window.innerWidth;b.i=this.window.innerHeight;b.j=!0;b.rect=g;this.b.Eb()&&(b=this.kb(b));return b}:this.M.Y==this.Z.IE&&/[6-9]|[10]/.test(this.M.ta)?this.ma=function(){if(8==document.documentMode)return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null};var a=this.window.Ra&&this.window.qa?this.window.Ra.Pb-
this.window.qa.Pb:0,g=this.window.Ra&&this.window.qa?this.window.Ra.Ob-this.window.qa.Ob:0,b=this.b.ya(this.window),c={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null};c.v=g;c.u=a;c.K=null;c.L=null;c.G=this.window.qa?g+this.window.qa.Fa:null;c.H=this.window.qa?a+this.window.qa.Ga:null;c.o=this.window.innerWidth||b.clientWidth;c.i=this.window.innerHeight||b.clientHeight;c.j=!0;c.rect={left:g,top:a,right:g+(this.window.innerWidth||b.clientWidth),bottom:a+(this.window.innerHeight||
b.clientHeight)};this.b.Eb()&&(c=this.kb(c));return c}:this.b.tb()?(c=512,this.ma=function(){var a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null};null!=this.c&&(adData=this.b.mb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.i=adData?adData.h:this.window.innerHeight);return a}):this.ma=this.M.Y==this.Z.Chrome?function(){var a=null,g=null,b=!1;try{var c=this.window.frameElement.offsetTop,a=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
g=c-this.window.frameElement.offsetParent.scrollTop,b=!0}catch(k){}c={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null};c.v=a;c.u=g;c.K=null;c.L=null;c.G=null;c.H=null;c.o=this.window.innerWidth;c.i=this.window.innerHeight;c.j=b;c.rect=b?{left:a,top:g,right:a+this.window.innerWidth,bottom:g+this.window.innerHeight}:null;this.b.Eb()&&(c=this.kb(c));return c}:null!=this.ga&&this.ga.Va()?function(){var a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,
rect:null,O:null,oa:null};null!=this.c&&(adData=this.b.mb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.i=adData?adData.h:this.window.innerHeight);return a}:function(){return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null}}:this.ma=function(a){var g=this.Yb(this.c,this.window),b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,i:null,j:!1,rect:null,O:null,oa:null},c=this.b.ac(this.c,this.window),k=this.b.uc(this.c,this.window);b.v=k.left;b.u=k.top;b.K=
g.x;b.L=g.y;b.G=a.I+k.left;b.H=a.J+k.top;b.o=k.w;b.i=k.h;b.j=!0;b.rect=c;b.O=k;return b};return this.ma(a,d)};this.kb=function(a){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return a;var c=this.b.mb(this.c);if(c){var d=c.w,g=c.h,b=a.v,e=a.u,x=a.H,f=a.G;null!=a.v&&null!=a.u&&null!=a.i&&null!=a.o&&a.rect&&(0<c.t?(e=a.u+c.t,null!=a.H&&(x=a.H+c.t)):g+=c.t,0<c.l?(b+=c.l,null!=a.G&&(f=a.G+c.l)):d+=c.l,c.r>a.o&&(d-=c.r-a.o),c.Cc>a.i&&(g-=c.Cc-a.i),a.o=0<d?d:0,a.i=0<
g?g:0,a.v=b,a.u=e,a.H=x,a.G=f,a.rect.left=a.v,a.rect.top=a.u,a.rect.right=a.v+c.w,a.rect.bottom=a.u+c.h,a.O={w:d,h:g,left:b,right:b+d,top:e,bottom:e+g})}return a};this.De=function(){var a=screen.availWidth,c=screen.availHeight,d=screen.width,g=screen.height,b=0,e=0;this.Sc&&(e=this.window.top,b=e.screenX,e=e.screenY);return{j:this.N.Ua?!1:"undefined"!==typeof b,zb:a||d,yb:c||g,Pf:b,Qf:e,Aa:b-(d-a),qf:e-(g-c)}};this.me=function(){var a=this.De(),c=this.na(a),d=this.ma(c,a);return{ea:c,f:d,va:a,Fb:(null==
c.I||null==c.J?0:this.ia.Nd)|(null==c.D||null==c.C?0:this.ia.Od)|(null==d.v||null==d.u?0:this.ia.Id)|(null==d.K||null==d.L?0:this.ia.Kb)|(null==d.G||null==d.H?0:this.ia.Hd)|(null==d.i||null==d.o?0:this.ia.Lb)|(null==a.yb||null==a.zb?0:this.ia.Md),P:this.Hc(d.i,d.o)}};this.Hc=function(a,c){null==a&&(a=0);null==c&&(c=0);return 1!=this.N.Ua?242500<=a*c:!1};this.ue=function(){this.b.a("c10");if(null!=this.c)if(this.b.Xc(this.c,this.window))try{var a={timeStamp:new Date,m:-3,ja:-3,s:null,P:!1,fa:0};if(!this.ec())return a;
var d=this.me(),e;if(!d.f.j||!d.ea.j){if(this.b.ua(this.window)&&this.window.$sf.ext.inViewPercentage)return e=this.window.$sf.ext.inViewPercentage(),{timeStamp:new Date,m:e,ja:e,s:d,P:d.P,fa:16};if(this.b.tb()&&this.rb)return e=0,null!=this.qb&&(e=Math.round(100*this.qb.intersectionRatio)),{timeStamp:new Date,m:e,ja:e,s:d,P:this.Hc(d.f.i,d.f.o),fa:512};if(this.ga.Va()){var g={timeStamp:new Date,m:-3,ja:-3,s:null,P:!1,fa:2};if(0==this.ga.Re())g.m=-6,g.ja=-6,this.ga.sd(this.window,this.c);else{var b=
this.ga.He();null!=b&&(g.s=d,g.P=d.P,g.m=b,g.ja=b)}return g}a.s=d;c&&(a.fa=c);return a}if(d.f&&d.f.O&&(0===d.f.O.w||1===d.f.O.w||0===d.f.O.h||1===d.f.O.h))return{timeStamp:new Date,m:-5,ja:-5,s:d,fa:c};e=d.f.O?this.Zb(d.va,d.f.O,d.ea,d.f.rect):this.Zb(d.va,d.f.rect,d.ea);return{timeStamp:new Date,m:e,ja:e,s:d,P:d.P,fa:c}}catch(u){return{timeStamp:new Date,m:-4,ja:-4,s:null,P:!1,fa:c}}else return{timeStamp:new Date,m:-2,ja:-2,s:null,P:!1,fa:0};else return{timeStamp:new Date,m:-1,ja:-1,s:null,P:!1,
fa:0}};this.ne=function(a,c){this.b.a("c11");var d=null,g=null;if(null!=a.s){var b=a.s.f;c<=this.N.bf&&(d=0<=a.m||-5==a.m?a.P&&a.m>=this.N.Wa||0==a.P&&50<=a.m?!0:!1:null,g=a.P?this.N.Wa/100:.5,g=0==d?0>b.u+b.i*g?!0:!1:1==d?!1:null)}return{Uc:g,Vc:d}};this.sb=function(a){this.b.a("c12");var c=null;if(2!=a.fa&&512!=a.fa&&null!=a.s){var d=a.s.Fb,g=a.s.f;(d&this.ia.Kb)==this.ia.Kb&&(d&this.ia.Lb)==this.ia.Lb&&(c=this.Zb(a.s.va,{left:g.K,top:g.L,right:g.K+g.o,bottom:g.L+g.i},a.s.ea,g.rect),c=0<=a.m?a.P&&
c>=this.N.Wa||0==a.P&&50<=c?!1:!0:null)}this.b.a("c12e");return c};this.hd=function(){function a(c){c.forEach(function(a){d.qb=a})}var d=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(c=512,this.wb=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.wb.observe(this.c),this.rb=!0)};this.Je=function(){this.c=null;null!=this.wb&&(this.wb.disconnect(),this.qb=null,this.rb=!1)}}
function P(){this.getElementVolume_object=function(a){var d=a.getAttribute("width"),e=a.getAttribute("height");null==d||""==d||null==e||""==e?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:d,h:e};return a};this.Se=function(a){var d=0;try{for(;null!=a&&10>d;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;d++}}catch(e){}return!0};this.aa=function(a,d){this.a("cm1");var e=null,h=a.nodeName.toLowerCase();d&&this["getElementVolume_"+
h]&&(e=this["getElementVolume_"+h](a));if(!e&&(e=this.mb(a),this.a("cm2e"),!e||1>=e.w||1>=e.h))return this.a("cm1e"),{w:0,h:0};e.w.indexOf&&e.w.indexOf("px")&&(e.w=e.w.replace("px",""));e.h.indexOf&&e.h.indexOf("px")&&(e.h=e.h.replace("px",""));this.a("cm1e");return e};this.mb=function(a){this.a("cm2");try{var d;return document.body.getBoundingClientRect&&(d=a.getBoundingClientRect())?{w:d.right-d.left,h:d.bottom-d.top,l:d.left,t:d.top,Cc:d.bottom,r:d.right}:null}catch(e){return null}};this.ya=function(a){return a.document.documentElement.clientHeight?
a.document.documentElement:a.document.body};this.Nc=function(a,d){this.a("ff9");var e=0,h=!1;if(a.document.all)for(var n=0;n<a.document.all.length;n++)"BODY"==a.document.all[n].nodeName&&(h=!0),h&&("width"==d?a.document.all[n].width>e&&(e=a.document.all[n].width):a.document.all[n].height>e&&(e=a.document.all[n].height));this.a("ff9e");return e};this.$c=function(a,d){for(var e=this.ya(a),h=a.innerWidth||e.clientWidth||this.Nc(a,"width"),e=a.innerHeight||e.clientHeight||this.Nc(a,"height"),n=d.length,
l=0,r=0;r<n;r++)if(15>=Math.abs(h-d[r].w)){l=d[r].h.length;for(h=0;h<l;h++)if(15>=Math.abs(e-d[r].h[h]))return!0;break}return!1};this.Df=function(a){for(var d=[],e=-1;d[++e]=a[e];);d.length--;return d};this.Hb=function(a,d,e,h){var n=a.getElementsByTagName("*"),n=this.Df(n);n.unshift(a);for(var l=["EMBED","IFRAME","OBJECT","IMG","DIV"],r=[],p=0;p<n.length;p++){var c=n[p];if(-1!=l.indexOf(c.nodeName)){var k=h(c);k&&r.push({Bc:k.w*k.h,w:k.w,h:k.h,type:c.nodeName||"other",ie:c})}}r=r.sort(function(a,
c){return c.Bc-a.Bc||l.indexOf(c.type)-l.indexOf(a.type)});(d=0<r.length&&r[0].w>d&&r[0].h>e?r[0].ie:null)&&a&&(d.pb=a.pb);return d};this.Xc=function(a,d){this.a("ff10");try{if(!a)return!1;for(d||(d=window);a!=d.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==d.document}catch(e){return!1}};this.ac=function(a,d){var e=d.parent,h={left:0,right:0,top:0,bottom:0};if(a){var n=a.getBoundingClientRect();d!=e&&this.Mb(d,e)&&(h=this.ac(d.frameElement,e));h={left:n.left+h.left,right:n.right+
h.left,top:n.top+h.top,bottom:n.bottom+h.top}}return h};this.Mb=function(a,d){var e=!1;if(a==d)e=!0;else try{a.document.domain==d.document.domain&&(e=!0)}catch(h){}return e};this.ve=function(a){if(a)try{if(a.contentDocument&&this.Wc(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.vb(a.contentWindow))return a.contentWindow.document}catch(d){}return null};this.Rc=function(a){return a?a.defaultView||a.parentWindow:null};this.Me=function(a,d){return-1<d.indexOf(a)};this.pe=function(a){try{return a!=
a.top&&a.parent&&this.vb(a.parent)?a.parent:null}catch(d){return null}};this.vb=function(a){try{return a&&a.document&&this.Wc(a.document)?!0:!1}catch(d){return!1}};this.Wc=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(d){return!1}};this.uc=function(a,d){var e=d.parent,h={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(h=this.ac(a,d),h.w=h.right-h.left,h.h=h.bottom-h.top,d!=e&&this.Mb(d,e)&&(e=this.uc(d.frameElement,e),e.bottom<h.bottom&&(e.bottom<h.top&&(h.top=e.bottom),
h.bottom=e.bottom),e.top>h.top&&(e.top>h.bottom&&(h.bottom=e.top),h.top=e.top),e.right<h.right&&(e.right<h.left&&(h.left=e.right),h.right=e.right),e.left>h.left&&(e.left>h.right&&(h.right=e.left),h.left=e.left),h.w=h.right-h.left,h.h=h.bottom-h.top));return h};this.Sb=function(a,d){return function(){return a.apply(d,arguments)}};this.ra=function(a){try{return a?a.length?a.length:0:0}catch(d){return 0}};this.cc=function(a){for(var d=[],e=0;e<a.length;e++)this.Se(a[e])&&d.push(a[e]);return d};this.a=
function(a){try{maxLength=3,$dv&&($dv.Ma=$dv.Ma||[],$dv.Ma.push(a),$dv.Ma.length>maxLength&&$dv.Ma.shift())}catch(d){}};this.ye=function(){try{return $dv&&$dv.Ma?$dv.Ma.join():""}catch(a){return""}};this.ua=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=this.La(a),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.ua=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;this.ua=function(){return!1};return!1};this.La=function(a){a.$sf.ext.geom&&(this.La="function"==typeof a.$sf.ext.geom?
function(a){return a.$sf.ext.geom()}:function(a){return a.$sf.ext.geom});return this.La(a)};this.F=function(a,d){if(null!=a&&null!=d)for(var e in d)d.hasOwnProperty(e)&&(a[e]=d[e])};this.jc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.tb=function(){var a=!1;if(1==this.lb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.ub=function(a,d,e){var h=e&&e.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(e&&e.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&
d.Y===h.Safari&&(null===d.ta||void 0===d.ta||!/^[3-8]/.test(d.ta)))return this.ub=function(){return!0},!0;this.ub=function(){return!1};return!1};this.lb=function(a){var d,e=this.Lc();e&&e.AVO&&(d=e.AVO[a]);return d};this.Lc=function(){var a={},d=window.$dv,e=window.$uid;d.tags&&d.tags[e]&&(a=d.tags[e]);return a};this.Eb=function(){return 1==this.lb("sam")?!0:!1};this.Ta=function(a){return a.document.hasFocus()};this.Ka=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(d,
e,h,n,l){if("undefined"==typeof n||null==n)n=window;n.addEventListener(d,e,h);l&&a.cache.push([d,e,h,n])}:window.attachEvent?a.add=function(d,e,h,n,l){if("undefined"==typeof n||null==n)n=window;n["e"+d+e]=e;n[d+e]=function(){n["e"+d+e](window.event)};n.attachEvent("on"+d,n[d+e]);l&&a.cache.push([d,e,h,n])}:a.add=function(){};window.removeEventListener?a.remove=function(a,e,h,n){if("undefined"==typeof n||null==n)n=window;n.removeEventListener(a,e,h)}:window.detachEvent?a.remove=function(a,e,h,n){if("undefined"==
typeof n||null==n)n=window;n.detachEvent("on"+a,n[a+e]);n[a+e]=null;n["e"+a+e]=null}:a.remove=function(){};a.flush=function(){for(var d=0;d<a.cache.length;d++)a.remove.apply(a,a.cache[d]);a.cache=[]}};this.getElementsByClassName=function(a,d){return a.getElementsByClassName?a.getElementsByClassName(d):a.querySelectorAll?a.querySelectorAll("."+d):[]};this.Ua=function(){var a=!1;if($dv&&$dv.CommonData){var d=$dv.CommonData.detectedDeliveryType;d&&0!=d?a=2==d||3==d:(d=$dv.CommonData.deviceType)&&(a=
2==d||3==d)}return a};this.xe=function(a,d){var e=a||"",h="";if(d&&(e+=": "+(d.message||""),d.stack)){var h=d.stack||"",n=h.indexOf("at ");0>n&&(n=0);h=", Stack: "+h.slice(n,h.length)}e=e.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");h=h.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");n=null;try{n=encodeURIComponent(e+h).slice(0,500)}catch(l){try{n=encodeURIComponent(e).slice(0,500)}catch(r){n=
e.slice(0,500)}}return n}}
function W(a,d,e,h,n,l){var r=new P;this.g=h;this.window=e;this.c=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.hc=null;this.M={Y:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.R=n;this.W=this.dvObj.Enums.TrafficScenario;this.U=d;this.A=l.A;115==this.dataObj.cb&&(this.A.B.h=20,this.A.B.w=20);this.nf=function(){l.ff(this.c);this.c=null};var p=[],c=["object","embed","img","iframe"];this.dataObj.spotXmode&&(c=["object","embed",
"video","iframe"]);this.Pe=function(a){r.a("a33");a=r.aa(a);return this.Qe(a)};this.Qe=function(a){if(a){var c=a.w;a=a.h;for(var e=d.length,g=0,b=0;b<e;b++)if(15>=Math.abs(c-d[b].w))for(var g=d[b].h.length,u=0;u<g;u++)if(15>=Math.abs(a-d[b].h[u]))return!0}return!1};this.se=function(){r.a("a34");return this.te()||this.rf()};this.rf=function(){r.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),c=[],d=window.parent;r.a("ff6");try{c=d.document.getElementsByTagName("script")}catch(b){}r.a("ff6e");
for(var d=c.length,g=0;g<d;g++)if(c[g]&&c[g].id&&c[g].id.substr(7)==a)return c[g];return null};this.te=function(){r.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Ud=function(a){r.a("a38");var d={node:a,xa:0};a=[];for(p=[];d||0<a.length;){try{var e;if(!(e=1==d.xa&&l.kc(d.node)&&!l.ka(d.node)&&l.S(d.node))){var g;a:{var b=d.node;try{if(b&&-1!=c.indexOf(b.nodeName.toLowerCase())){g=
!0;break a}}catch(h){}g=!1}e=g&&this.Pe(d.node)&&!l.ka(d.node)&&l.S(d.node)}if(e)return d;if(d.xa<=this.A.Ye){var u,x=d.node,f=d.xa,d=[],t=x.parentNode;t&&-1==p.indexOf(t)&&(p.push(t),d.push({node:t,xa:f+1}));if(x.hasChildNodes())for(var m=0;m<x.childNodes.length;m++)x.childNodes[m]&&-1==p.indexOf(x.childNodes[m])&&1===x.childNodes[m].nodeType&&(p.push(x.childNodes[m]),d.push({node:x.childNodes[m],xa:f+1}));var w,n=x,B=[],y=null;n&&n.parentNode&&(y=n.parentNode.firstChild);for(;y;)1===y.nodeType&&
y!==n&&B.push(y),y=y.nextElementSibling||y.nextSibling;w=B;for(m=0;m<w.length;m++)w[m]&&-1==p.indexOf(w[m])&&1===w[m].nodeType&&(p.push(w[m]),d.push({node:w[m],xa:f+1}));if(u=d)for(d=0;d<u.length;d++)a.push(u[d])}}catch(h){}d=a.shift()}return{node:null}};this.Ae=function(){r.a("a37");var a=this.se(),c=null;a&&(c=this.Ud(a));return c};this.ke=function(a){r.a("a31");if(this.c=l.ze())return this.g.yd(),this.hc=!0,this.c;if(this.dataObj.btreg&&!0===this.hc&&1<a)return this.c;"1"!=this.dataObj.displaynon&&
(a=this.Ae())&&a.node&&(this.g.xd(a.xa),this.c=a.node);return this.c};return this}
function X(a,d,e,h,n,l){function r(a,b){for(var c=[],d=0;d<q.length;d++){var f=[],f=b(a,q[d]),e=k.ra(f);if(0!=e){var m=k.Rc(q[d]);if(null!=m)for(var h=0;h<e;h++)try{f[h].pb=m,c.push(f[h])}catch(l){}}}return c}function p(a,b){return r(a,function(a,g){k.a("ff4");var f=g.getElementsByTagName(a);k.a("ff4e");return"1"!=b?f:k.cc(f)})}var c=this,k=new P,v="Microsoft Internet Explorer"==navigator.appName;this.dataObj=a;this.window=d;this.c=e;this.R=h;this.W=n;this.dvObj=void 0===l?l={}:l;this.A={B:{h:1,w:1},
Hf:{h:10,w:10},Ye:10};115==this.dataObj.cb&&(this.A.B.h=20,this.A.B.w=20);this.Ce=function(a){if(a.scanOrder)return a.scanOrder;var b=[1==v?"object":"embed",1==v?"embed":"object","href","img","span","iframe","frameElement","div"];a.findclass&&1==a.findclass&&b.push("classDeclaration");a.gb&&0<a.gb.length&&b.unshift("searchCustomElementsFromTag");return b};this.searchCustomElementsFromTag=function(a){for(var b=0;b<a.gb.length&&(c.Ic(a.gb[b],a),!c.c);b++);};this.Gb=[["DCF",'"'],[";",";"],["%3B","%3B"],
["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.ce=function(){var g=c.dataObj.jb+"-"+c.dataObj.ib;a.isBrandShieldOrigin&&(g+="-bs");return g.replace(RegExp(",","g"),";")};this.qc=this.ce();this.Ic=function(a,b){if(b.btreg)for(var d=p(a,b.displaynon),e=k.ra(d),f=0;f<e;f++)if(d[f]&&c.wa(b,d[f],!0)&&!c.ka(d[f])){var t=this.kc(d[f]);if(t&&(m=k.aa(t))&&m.h>c.A.B.h&&m.w>c.A.B.w&&c.S(t)){c.c=t;c.S(d[f]);break}var m=k.aa(d[f]);if(m&&m.h>c.A.B.h&&m.w>
c.A.B.w&&c.S(d[f])){c.c=d[f];break}if((t=k.Hb(d[f],c.A.B.w,c.A.B.h,k.Sb(k.aa,k)))&&c.S(t)){c.c=t;c.S(d[f]);break}}};this.div=function(a){this.Ic("div",a)};this.span=function(a){k.a("a10");if(a.btreg)for(var b=p("span",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e],!0)&&!c.ka(b[e])){var f=b[e];k.a("a20");if(f&&"1"==f.getAttribute("adunit")){c.c=b[e];break}if(f=this.kc(b[e])){var t=k.aa(f);if(t&&t.h>c.A.B.h&&t.w>c.A.B.w&&c.S(f)){c.c=f;c.S(b[e]);break}}if((f=k.Hb(b[e],c.A.B.w,c.A.B.h,k.Sb(k.aa,
k)))&&c.S(f)){c.c=f;c.S(b[e]);break}}};this.object=function(a){k.a("a11");for(var b=p("object",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&!c.ka(b[e])){var f=k.Hb(b[e],c.A.B.w,c.A.B.h,k.Sb(k.aa,k));if(f&&c.S(f)){c.S(b[e]);c.c=f;break}}};this.embed=function(a){k.a("a12");for(var b=p("embed",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&!c.ka(b[e])){var f=k.aa(b[e]);if(f&&f.h>c.A.B.h&&f.w>c.A.B.w&&c.S(b[e])){c.c=b[e];break}}};this.href=function(a){k.a("a13");for(var b=p("a",
a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&!c.ka(b[e])){var f=b[e].getElementsByTagName("img");if(0<f.length){var t=k.aa(f[0]);if(t&&t.h>c.A.B.h&&t.w>c.A.B.w&&c.S(b[e])){c.c=f[0];break}}}};this.img=function(a){k.a("a14");for(var b=p("img",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&0>b[e].src.indexOf("event")&&!c.ka(b[e])){var f=k.aa(b[e]);if(f&&f.h>c.A.B.h&&f.w>c.A.B.w&&c.S(b[e])){c.c=b[e];break}}};this.classDeclaration=function(a){k.a("a9");var b="undefined"!==typeof window.document.getElementsByClassName,
d="undefined"!==typeof window.document.querySelectorAll;if(a.btreg){var e=[];if(b)e=c.getElementsByClassName(a.btreg,a.displaynon);else if(d)e=c.querySelectorAll(a.btreg,a.displaynon);else return;a=k.ra(e);for(b=0;b<a;b++)if(e[b]&&!c.ka(e[b])&&(d=k.aa(e[b]))&&d.h>c.A.B.h&&d.w>c.A.B.w&&c.S(e[b])){c.c=e[b];break}}};this.iframe=function(a){k.a("a15");for(var b=p("iframe",a.displaynon),d=k.ra(b),e=0;e<d&&!c.xc(a,b[e]);e++);};this.frameElement=function(a){try{k.a("a16"),h==n.SameDomain&&c.xc(a,window.frameElement)}catch(b){}};
this.getElementsByClassName=function(a,b){return r(a,function(a,c){k.a("ff1");var f=c.getElementsByClassName(a);k.a("ff1e");return"1"!=b?f:k.cc(f)})};this.querySelectorAll=function(a,b){return r(a,function(a,c){k.a("ff3");var f=c.querySelectorAll("."+a);k.a("ff3e");return"1"!=b?f:k.cc(f)})};this.la=function(a,b){k.a("a28");return!a||!b||5>b.length?!1:null!=(c.vc?c.vc(a,b):c.Ib(a,b))?!0:c.Tb&&"function"===typeof c.Tb?c.Tb(a,b):!1};this.wa=function(a,b,d){k.a("a22");var e=null;return a.btreg&&(c.vc=
1==a.ad?c.Ed:c.Ib,e=c.Kd(a,b,d))||!c.c&&(e=c.Ld(a,b))?!0:!1};this.Pd=function(a){k.a("a21");if(a&&!c.ka(a)){var b=k.aa(a);if(b&&b.h>c.A.B.h&&b.w>c.A.B.w&&c.S(a))return c.c=a,!0}return!1};this.xc=function(a,b){k.a("a17");return c.wa(a,b)?c.Pd(b):!1};this.ka=function(a){k.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==c.qc)return!0}return!1};this.S=function(a){k.a("a18");if(a&&0==c.ka(a))try{var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",
b+","+c.qc):(k.a("ff5"),b=window.document.createAttribute("dvvisit"),k.a("ff5e"),b.value=c.qc,a.setAttributeNode(b));return!0}catch(d){}return!1};this.ff=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.Ed=function(a,b){k.a("a29");var d;try{d=(new RegExp(b)).exec(a)}catch(e){d=c.Ib(a,b)}return d};this.Ib=function(a,b){k.a("a30");var c=null;-1!==a.indexOf(b)&&(c=a);return c};this.kc=function(a){var b=null;"celtra-ad-v3"==a.className&&a.celtra&&1==a.celtra.loaded&&
(b=a.celtra.viewabilityObservee);b&&(b.pb=k.Rc(b.ownerDocument)||window);return b};var q=[];this.Kd=function(a,b,d){k.a("a23");var e;try{if(a.Fc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(e=c.la(b.id,a.btreg))||(e=c.la(b.src,a.btreg));e||(e=c.la(b.href,a.btreg));e||(e=c.la(b.getAttribute("flashvars"),a.btreg));e||(e=c.la(b.name,a.btreg));if(e&&1!=a.ad&&a.btreg==a.Ja){var f=k.aa(b);f&&f.h>c.A.B.h&&f.w>c.A.B.w&&$dv&&$dv.eventBus&&$dv.eventBus.dispatchEvent&&$dv.eventBus.dispatchEvent(window,
"avsAdFound",{timeStamp:(new Date).getTime(),adDomElement:b})}!e&&a.findclass&&1==a.findclass&&(e=c.la(b.getAttribute("class"),a.btreg));if(!e&&c.dataObj.Ia&&0<c.dataObj.Ia.length)for(var t=c.dataObj.Ia,f=0;f<t.length&&!(e=c.la(b.getAttribute(t[f]),a.btreg));f++);e||d||(e=c.la(b.innerHTML,a.btreg));e&&!d&&(e=c.Jd(a,b));return e}catch(m){return e}};this.Da=function(a,b){k.a("a25");if(!a)return!1;a=a.toLowerCase();for(var d=0;d<c.Gb.length;d++){var e;if(b.Ac&&(e=(c.Gb[d][0]+b.Ac).toLowerCase(),e=a.indexOf(e),
-1<e)||b.ed&&(e=(c.Gb[d][0]+b.ed).toLowerCase(),e=a.indexOf(e),-1<e))return!0}return!1};this.Ld=function(a,b){k.a("a24");var d;try{if(a.Fc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(d=c.Da(b.id,a))||(d=c.Da(b.src,a));d||(d=c.Da(b.href,a));d||(d=c.Da(b.Mf,a));d||(d=c.Da(b.name,a));d||(d=c.Da(b.innerHTML,a));if(!d&&c.dataObj.Ia&&0<c.dataObj.Ia.length)for(var e=c.dataObj.Ia,f=0;f<e.length&&!(d=c.la(b.getAttribute(e[f]),a.btreg));f++);return d}catch(t){return d}};this.Jd=function(a,b){k.a("a26");
return null==a.Ja||""==a.Ja?!1:c.la(c.Dd(b),a.Ja)};this.searchByAdSrvId_8=function(a,b){k.a("a1");var c=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=c&&(c=c.toString(),c.replace(RegExp("-","g"),"")==b)?!0:!1};this.Tb=this["searchByAdSrvId_"+(c.dataObj?c.dataObj.cb||"":"")];this.Dd=function(a){k.a("a27");if(a.outerHTML)return a.outerHTML;for(var b=a.attributes.length,c="",d=0;d<b;d++)c=c+a.attributes[d].nodeName+"="+a.attributes[d].nodeValue+" ";return c+a.innerHTML};this.ze=function(){k.a("32");
var a=[];void 0===l.tags&&(l.tags={});void 0===l.tags[$uid]&&(l.tags[$uid]={});void 0!==l.tags[$uid].spvi&&(a.push(l.tags[$uid].spvi),-1<a[0].scanOrder.indexOf(",")&&(a[0].scanOrder=a[0].scanOrder.split(",")));c.dataObj.scanOrder=this.Ce(c.dataObj);a.push(c.dataObj);var b=c.window,d=0,h=[];try{do{h.push(b.document);for(var f=h,t=b.document.getElementsByTagName("iframe")||[],m=0;m<t.length||25>m;m++){var w=null,w=k.ve(t[m]);void 0!==w&&null!==w&&0==k.Me(w,f)&&f.push(w)}b=k.pe(b)}while(b&&10>++d)}catch(n){}q=
h;for(b=0;b<a.length;b++)for(d=a[b],h=0;h<d.scanOrder.length;h++)if(void 0!=c[d.scanOrder[h]]&&(c[d.scanOrder[h]](d),c.c))return c.c;return e};return this}
function dv_CustomClientViewAssureService(a){function d(a){return{mf:{adView:a.rq.av,Le:a.rq.ic,yc:a.rq.adc,Xe:a.rq.mla,focus:a.rq.fc,zc:a.rq.as},lf:{dd:a.rp.mt,ef:a.rp.pt,Ze:a.rp.mr,df:a.rp.pr,eventId:a.rp.eid,Ec:a.rp.bl}}}this.Td=dv_InViewService;this.Td(a);this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new P;this.$a=[];a=$dv.tags[$uid].dc||a.dc||[];var e=this.b.Lc().bgm,h;for(h in a)a.hasOwnProperty(h)&&this.$a.push(new window.Xb.de(d(a[h]),e));var n=this.Jb;
this.Jb=function(a){a=n(a);for(var d=0;d<this.$a.length;d++)this.$a[d].fe(a,this.$.interval);return a};var l=this.Pa;this.Pa=function(a,d){l(a,d);if(1==this.Ub)for(var c=0;c<this.$a.length;c++)this.$a[c].af()}}window.Xb=window.Xb||{};
window.Xb.de=function(a,d){function e(a){a.s&&a.s.f&&a.s.f.i&&a.s.f.o&&242500<=a.s.f.o*a.s.f.i&&(l=!0,updateAdLarge=function(){})}var h=a.mf,n=a.lf,l=!1;this.fe=function(a,d){var l=!0,n;n=h.focus?a.m:a.ja;h.adView&&h.adView>n&&(l=!1);h.zc&&a.s&&a.s.f&&a.s.f.i&&a.s.f.o&&a.s.f.o*a.s.f.i<h.zc&&(l=!1);l?r+=d:h.Le&&(r=0);e(a);this.Yd(a)};var r=0;this.af=function(){this.hf(n.dd,n.Ze,n.Ec)};this.jd=function(){this.jf(n.dd,n.ef,n.df,n.Ec,n.eventId);this.jd=function(){}};this.Yd=function(a){(h.yc&&r>=h.yc||
l&&h.Xe)&&this.jd(a)};var p;this.hf=function(a,e,h){d&&h||(a&&(p=$dv.tags[$uid].getTimeDiff(),h={},h[a]=p,$dv.registerEventCall($uid,h)),e&&($dv.pubSub.publish(e,$uid),window&&$dv.pubSub.publish(e,window.$frmId)))};this.jf=function(a,e,h,l,g){d&&l||(e&&(l={},l[e]=$dv.tags[$uid].getTimeDiff(),g&&(l.evid=g),a&&(l[a]=p||$dv.tags[$uid].getTimeDiff()),$dv.registerEventCall($uid,l)),h&&($dv.pubSub.publish(h,$uid),window&&$dv.pubSub.publish(h,window.$frmId)))}};
function dv_InViewService(a){function d(){null===l.interval&&(l.interval=setInterval(l.we(),l.$.interval))}function e(){if(!1===l.Zc){l.Zc=!0;try{l.b.Ka.remove("load",arguments.callee,!1,element)}catch(a){}l.Ab();l.b.a("s41");l.sa=new V(l.Xd?l.Xd:l.window,l.c,l.R,l.M,l.N,l.g.Gc,l.dvObj,l.impressionId);l.b.a("s42");l.Gd();l.start()}}function h(a,b){return a.isReportingDisabled?new R:new Q(a,b)}function n(a,b){l.b.Ka.add("click",function(){l.Nb(!0);$dv.registerEventCall(l.impressionId,"ad"==b?{dvp_csad:1}:
{dvp_csifr:1});l.b.Ka.remove("click",arguments.callee,!1,a)},!1,a,!1)}var l=this;this.cd=10;this.Sd=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"666";this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new P;this.Ie=function(){for(var a=document.getElementsByTagName("script"),b=a.length,d,c=0;c<b;c++)if(d=a[c].src,/visit[.]js/.test(d))return d.substring(d.indexOf("?")+1)};var r=this.Zc=!1,p=!1;this.Fe=function(){var a=
"";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.Qc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.V=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var d=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return d=d?d[1]:null};this.Ge=function(){var a=this.V("uid",this.ca);null==
a?(a=this.Qc(),this.ca=this.ca+"&uid="+a):""==a&&(a=this.Qc(),this.ca=this.ca.replace("&uid=","&uid="+a));return a};this.oc=function(a,b,d,c){if(c&&c.insertBefore&&c.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in d)a.style[e]=d[e];c.insertBefore(a,c.firstChild);return a}return null};this.Wd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};
this.R=this.dvObj.CommonData.Scenario||this.Wd();this.M={Y:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.W=this.dvObj.Enums.TrafficScenario;this.Xa="default";this.dataObj=a;this.window=a.tagWindow||parent.window||window;this.c=null;this.sc=this.Qa=!1;this.lc=!0;this.interval=null;this.ca=this.Ie();this.Ba=this.Fe();a.serverSettings&&a.serverSettings.protocol&&a.serverSettings.protocol.indexOf("http");this.$=window.he||this.window.he||
{interval:100,za:{"default":{time:null,Ka:["beforeunload","unload"],td:9E5}}};this.gd={};var c=null;this.T=window.ge||this.window.ge||{interval:1E3,ba:6};var k=a&&a.vd?a.vd:!1;a=a&&a.wd?a.wd:!1;!1!==k&&!1!==a&&(this.T.interval=k,this.T.ba=a,$dv.registerEventCall(this.impressionId,{Kf:this.T.interval,Lf:this.T.ba}));k=this.b.Ua();this.ae={hb:12,Wb:10,Wa:30};this.N={Firefox:{X:115},Chrome:{X:89},Safari:{X:38},Explorer:{X:55},bf:500,Ua:k,Wa:30};var v=!1,q=0,g=[5,10,15];window.devicePixelRatio&&(this.N.Firefox.X=
0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.U=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},
{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180]},{w:980,h:[90,
120]},{w:900,h:[240]}];this.dataObj.spotXmode&&(this.U.push({w:320,h:[240]}),this.U.push({w:400,h:[300]}),this.U.push({w:450,h:[338]}),this.U.push({w:600,h:[800]}),this.U.push({w:640,h:[360]}),this.U.push({w:854,h:[480]}),this.U.push({w:500,h:[375]}));k&&(this.U.push({w:320,h:[50,100,480]}),this.U.push({w:300,h:[50,31]}),this.U.push({w:120,h:[20]}),this.U.push({w:168,h:[28]}),this.U.push({w:216,h:[36]}),this.U.push({w:292,h:[30]}));this.ob=this.Ge();this.Vb=!1;this.Oa=function(a,b){this.window.Jc||
(this.window.Jc=[]);this.window.Jc.push({caller:a,Nf:b})};this.startTime=(new Date).getTime();this.Qd=4;this.wc=0;this.ec=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,If:17,interval:32};this.Ub=!1;this.ud=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.g.qe();this.window.dv_logObject[this.ob]=a}this.b.a("ie16e")};this.Db=function(a){this.b.a("ie17");this.Db=this.Vb?function(a){this.g.od(a);
this.ud()}:function(a){this.g.od(a)};this.Db(a)};this.rc=function(a,b){this.rc=this.Vb?function(a,f){this.g.nd(a,f);this.ud()}:function(a,f){this.g.nd(a,f)};this.rc(a,b)};this.Ab=function(){this.b.a("s4");this.c=this.Qb.ke(this.T.ba);!this.c&&this.R==this.W.CrossDomain&&this.b.ua(this.window)&&(this.T.ba=0);if(this.c)this.sf(),this.g.gf(this.c),r||(n(this.c,"ad"),r=!0),p||this.R!=this.W.CrossDomain&&this.R!=this.W.SameDomain||(n(window.parent,"ifr"),p=!0),setTimeout(d,this.Qb.hc?10:50);else if(0<
this.T.ba)this.T.ba--,this.tf(),setTimeout(this.le(),this.T.interval);else{try{this.R==this.W.CrossDomain&&(this.b.$c(this.window,this.U)||this.b.ua(this.window))?(this.c=this.b.ya(this.window),this.g.md()):this.R==this.W.SameDomain&&this.b.$c(this.window,this.U)?(this.c=this.b.ya(window.parent),this.g.md(),this.$d()):this.T.ba=-1}catch(a){this.T.ba=-1}setTimeout(d,10)}this.b.a("s4e")};this.$d=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),
d=b.length,c=0;c<d;c++)b[c].contentWindow==a&&(this.c=b[c],this.window=a.parent);this.b.a("ff26e")};this.tf=function(){this.dataObj.btreg&&this.dataObj.Ja?this.g.xf():this.g.yf()};this.sf=function(){this.b.a("s9");this.Qa=!0;this.g.uf();this.b.a("s9e")};this.Rd=function(){this.dataObj.cb=this.V("adsrv",this.ca)||"";this.dataObj.btreg=this.V("btreg",this.ca)||"";this.dataObj.ed=this.V("plcid",this.ca)||"";"8"==this.dataObj.cb&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.Ja=
this.V("btadsrv",this.ca)||"";this.dataObj.Ac=this.V("adid",this.ca)||"";this.dataObj.ob=this.ob;this.dataObj.ad=this.V("isbtregex",this.Ba)||"";this.dataObj.jb=this.V("ctx",this.ca)||"";this.dataObj.ib=this.V("cmp",this.ca)||"";this.dataObj.Te=this.V("lomd",this.Ba)||"";this.dataObj.findclass=this.V("findclass",this.Ba)||"";this.dataObj.displaynon=this.V("displaynon",this.Ba)||"";this.dataObj.Fc=this.V("bsdvview",this.Ba)||"";var a=this.V("bttag",this.Ba)||"";this.dataObj.gb=0<a.length?a.split("|"):
[];a=this.V("btattb",this.Ba)||"";this.dataObj.Ia=0<a.length?a.split("|"):[]};this.fd=function(a){a=this.xb(a);return 0<a.length?{tagServiceResult:a.join(",")}:{}};this.xb=function(a){if(!this.dvObj)return[];for(var b=[],d=0;d<a.length;d++){var c=this.dvObj.pubSub.publish(a[d],this.impressionId)||null;null!=c&&b.push(c);window&&(c=this.dvObj.pubSub.publish(a[d],window.$frmId)||null,null!=c&&b.push(c))}return b};this.zd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.ca+=
"&TKH="+this.dataObj.serverSettings.TKH)};this.ee=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),d=b.length>>>0;if(0===d)return-1;var c=0;1<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=d)return-1;for(c=0<=c?c:Math.max(d-Math.abs(c),0);c<d;c++)if(c in b&&b[c]===a)return c;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.ee();this.zd();this.Rd();
this.g=new G(this.Sd,this.ae,this.dataObj);this.ha=h(this.dataObj,this.g);this.dataObj.isRTNsDisabled&&(this.xb=function(){return[]});this.Vb=this.window.dv_logObject?!0:!1;this.zf();this.Vd=new X(this.dataObj,this.window,this.c,this.R,this.W,this.dvObj);this.Qb=new W(this.dataObj,this.U,this.window,this.g,this.R,this.Vd);var a=window.parent;"589953"==this.dataObj.jb&&"587351"==this.dataObj.ib||"589953"==this.dataObj.jb&&"616389"==this.dataObj.ib||"polite"==this.dataObj.Te?(setTimeout(e,15E3),this.b.Ka.add("load",
function(){setTimeout(e,1E3)},!1,a,!1)):e()}catch(b){var c=this;this.Ea(function(){c.Oa("inViewManager",b);c.g.Za("inViewManager",b);c.ha.da(c.logEvents.errorlevel1)},"inViewManager",b)}};this.ab=function(a){this.b.a("ie20");-6!=a.m&&(-3==a.m||-5!=a.m&&0>a.m&&-1==this.T.ba)&&(this.tc(),this.ab=function(){})};this.tc=function(){this.ha.da(this.logEvents.nonMeasurable);this.xb(["IABNotMeasuredImpression"]);this.tc=function(){}};this.Pa=function(a,b){a.b.a("ie21");if(0<=b.m||-5==b.m&&-1>=a.T.ba){if(a.dvObj&&
a.impressionId){a.b.a("ie23");var c=a.fd(["IABMeasuredImpression"]);a.b.a("ie24");a.ha.da(a.logEvents.startMeasure,c)}else a.ha.da(a.logEvents.startMeasure);a.Ub=!0;a.Pa=function(){};a.ab=function(){}}a.b.a("ie22")};this.Nb=function(a){this.b.a("ie25");if(this.g.Mc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.fd(["IABViewableImpression"]),this.b.a("ie29"),this.ha.da(this.logEvents.iabViewable,a)):this.ha.da(this.logEvents.iabViewable),v=!0,this.Nb=function(){};
this.b.a("ie26")};this.be=function(a){if(v&&this.g.Mc())for(q+=a,a=0;a<g.length;a++)null!=g[a]&&q>=1E3*g[a]&&(this.xb(["IABAdViewable"+g[a]+"Seconds"]),g[a]=null);else q=0};var b="hidden",u=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(var a in vis)if(vis[a]in document){b=vis[a];break}a=1==this.b.lb("fcs");var c=!1;try{this.b.Ta(this.window),c=!0}catch(d){}var e=!1;try{this.b.Ta(this.window.top),e=!0}catch(d){}var g=null,g=a&&c&&this.M.Y==this.Z.IE?
function(){var a=l.b.Ta(l.window);l.R==l.W.OnPage&&(a=a&&l.lc);return a}:a&&e?function(){var a=!0,a=l.b.Ta(l.window.top);l.R==l.W.OnPage&&(a=a&&l.lc);return a}:"undefined"!==typeof document[b]?function(){return!l.window.document[b]}:e?function(){return l.b.Ta(l.window.top)}:function(){return!0};this.hasFocus=function(){try{return g()}catch(a){u++,5<=u&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.bc=function(a){var b=a.sa.ue();a.b.a("ie12");0>b.m&&this.g.Cb(Math.abs(b.m));
null==this.c||-3==b.m||a.hasFocus()||(b.m=0,this.g.Cb(9));a.b.a("ie13");return c=b};var x;this.Jb=function(a){var b;try{$uid&&dvObj&&dvObj.tags[$uid]&&dvObj.tags[$uid].getTimeDiff&&(b=dvObj.tags[$uid].getTimeDiff())}catch(c){}a.$.interval=b-x||100;x=b;a.b.a("ie1");b=a.c?a.c.pb||a.window:a.window;a.sa.c=a.c;a.sa.window=b;a.b.a("ie2");b=a.bc(a);a.Qa&&(-1==b.m||-2==b.m)&&-1<=a.T.ba&&(a.kd(a),a.Ab());a.b.a("ie3");-5==b.m&&(a.T.ba--,a.g.pd(),a.Na||(a.Na=function(b){b=a.sa.sb(b);a.g.Ya(b)}));a.b.a("ie4");
a.Na&&0<b.m&&(a.Na(b),a.Na=null);a.b.a("ie5");if(a.Qa&&!a.sc){a.sc=!0;var d=a.sa.sb(b);a.g.Ya(d)}-5==b.m&&-1<=a.T.ba&&(a.kd(a),a.Ab(),b=a.bc(a),-5==b.m&&0<a.T.ba&&a.g.pf());a.b.a("ie6");a.rc(b,a.$.interval);a.b.a("ie7");a.Db(b);a.b.a("ie8");a.g.rd(b.fa);a.ab(b);a.b.a("ie9");a.Pa(a,b);a.b.a("ie10");a.Nb();a.b.a("ie11");a.be(a.$.interval);a.b.a("ie12");return b};this.kd=function(a){a.Qa=!1;a.c=null;a.Qb.nf();a.sa.Je()};this.we=function(){this.b.a("s26");var a=this;return function(){try{a.Jb(a)}catch(b){a.Ea(function(){a.wc<
a.Qd&&(a.wc++,a.Oa("getIntervalCallback",b),a.g.Za("getIntervalCallback",b),a.ha.da(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Pc=function(a){var b=this;return function(){b.Ea(function(){b.ha.da(b.logEvents[a])},"getReportEventCallback")}};this.le=function(){var a=this;return function(){a.Ea(function(){a.Ab();a.c||a.g.Bb()},"getAdLocateCallback")}};this.Sa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.lc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ea(function(){a.Oa("getFocBluEventCallback",
c);a.g.Za("getFocBluEventCallback",c);a.ha.da(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.Fd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.g.re().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*
c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.Ub,totalPageTime:(a.g.$b()-a.g.Ee())/1E3,notApplicableTime:a.g.Oc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Gd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=c.m;0<=c.m&&c.s&&c.s.f&&(a.adWidth=c.s.f.o,a.adHeight=c.s.f.i);return a};a.VA.getAdElem=function(){return l.c}}}catch(b){}};this.Fd();this.start=
function(){this.b.a("s35");this.cf(this);var a;this.$&&this.$.za&&this.$.za[this.Xa]&&(a=this.$.za[this.Xa].Ka);if(a)for(var b=a.length,c=0;c<b;c++)this.gd[a[c]]=this.Pc(a[c]),this.Ha(this.window,a[c],this.gd[a[c]]);this.Bf();this.$&&this.$.za&&this.$.za[this.Xa]&&this.$.za[this.Xa].td&&setTimeout(this.kf(),this.$.za[this.Xa].td)};this.kf=function(){var a=this;return function(){a.Pc("timeout")();clearInterval(a.interval);a.ha.da=function(){}}};this.cf=function(a){try{var b=a.bc(a);-5==b.m&&(this.g.pd(),
this.Na||(this.Na=function(b){b=a.sa.sb(b);a.g.Ya(b)}));if(a.Qa)if(this.sc=!0,-5!=b.m){var c=a.sa.sb(b);a.g.Ya(c)}else a.g.Ya("true");a.g.rd(b.fa);var d=a.sa.ne(b,a.g.Oc());a.g.wf(d);a.g.qd(b.m);a.Db(b);a.ab(b);a.Pa(a,b)}catch(e){a.Ea(function(){a.Oa("onStartReport",e);a.g.Za("onStartReport",e);a.ha.da(a.logEvents.errorlevel1)},"onStartReport",e)}};this.Bf=function(){this.Ha(this.window,"blur",this.Sa());this.Ha(this.window,"focus",this.Sa());this.Ha(this.window.document,"click",this.Sa());this.Ha(this.window.document,
"mousedown",this.Sa());this.Ha(this.window.document,"mouseup",this.Sa())};this.Ha=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.zf=function(){this.b.a("ff24");this.R==this.W.CrossDomain?this.b.ua(this.window)||this.b.jc(this.window)||this.b.tb()||this.b.ub(this.R,this.M,this.dvObj)||(this.M.Y!=this.Z.Firefox&&
this.M.Y!=this.Z.IE?this.g.Af():this.M.Y==this.Z.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.g.pc()):window.document.body.getBoundingClientRect||this.g.pc();this.ec=this.g.Gc();this.b.a("ff24e")};this.Ea=function(a,b,c){try{a()}catch(d){try{0<this.cd&&(this.cd--,a=c||d,b=b||"unknown caller",this.Oa(b,a),this.g.Za(b,a),this.ha.da(l.logEvents.errorlevel1))}catch(e){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||a.cvmSettings||a.billable?(new dv_CustomClientViewAssureService(a)).inViewManager():(new dv_InViewService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=
Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs666");if(tagObject){var serviceParams=tagObject.services.avs666;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
